### ISSUE TITLE
CI / unit tests

### ISSUE THREAD

**Issue by DanielRuf** [FriendsOfShopware/FroshViewSnapshots#6]
## Actual behaviour

Currently there are no unit tests which are tested on CI

## Expected behaviour

There should be unit tests for `composer test`.

## Steps to reproduce

1. Check results of the CI builds

## Checklist

- [ ] I have checked [all issues](https://github.com/FriendsOfShopware/FroshViewSnapshots/issues?q=is%3Aissue+is%3Aopen+is%3Aclosed) and haven't found a similar report.
- [ ] I am using the latest stable version of this plugin.

--

**Comment by dneustadt** [comment]
Added some functional tests to the 1.1 branch. 🍰
